name: pr
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: run lint check
      run: npm run lint
